version: '3.1'
services:
  nginx:
    container_name: "nginx"
    image: nginx:alpine
    restart: always
#    volumes: map local with service
#      - ./data/:xxxx
    ports:
      - 81:80

  nginx2:
    container_name: "nginx2"
    image: nginx:alpine
    restart: always
#    depends_on: wait service nginx successful
#      - nginx
    ports:
      - 82:80

